<?php
namespace Approach\Imprint\test\hellotoken;
use \Approach\Render as ProjectRender;
use \Approach\Render;
	
	/**
	* This class was generated by Approach\Imprint::Mint()
	* It can be used to create a new Render tree based on the original Pattern
	*/
	class hello extends Render\Node
	{
	public static array $tokens = [
		
	];
	public array $token_nodes = [];
	
	public function __construct(array $tokens = [])
	{
		$Node_0 = new Render\Node( );
	// Instantiating HTML_0__tag for upcoming tag assignment
		$HTML_0__tag = new Render\Node( );
			// Instantiating HTML_1__tag for upcoming tag assignment
				$HTML_1__tag = new Render\Node( );

			// Instantiating HTML_1__classes for upcoming classes assignment
				$HTML_1__classes = new Render\Node( );

			// Instantiating HTML_1__attributes for upcoming attributes assignment
				$HTML_1__attributes = new Render\Attribute( );

			$HTML_0__tag[] = $HTML_1 = new Render\HTML( tag: $HTML_1__tag, classes: $HTML_1__classes, attributes: $HTML_1__attributes );


	// Instantiating HTML_0__classes for upcoming classes assignment
		$HTML_0__classes = new Render\Node( );

	// Instantiating HTML_0__attributes for upcoming attributes assignment
		$HTML_0__attributes = new Render\Attribute( );

	$Node_0[] = $HTML_0 = new Render\HTML( tag: $HTML_0__tag, classes: $HTML_0__classes, attributes: $HTML_0__attributes );


		foreach($tokens as $key => $value){
			$this->token_nodes[$key]->content = $tokens[$key];
		}
		$this->nodes[] = $Node_0;
	}
}
