<?php

namespace Approach\Imprint\test\if;
use \Approach\Render as ProjectRender;
use \Approach\Render;

/**
 * This class was generated by Approach\Imprint::Mint()
 * It can be used to create a new Render tree based on the original Pattern
 */
class if extends Render\Node
{
    public array $tokens = [];

    public function __construct(array $tokens = [])
    {
        $Node_0 = new Render\Node( );
	// Instantiating ifNode_0__condition for upcoming condition assignment
		$ifNode_0__condition = $this->tokens['false_token'] = new Render\Token( name : 'false_token' );

	$Node_0[] = $ifNode_0 = new Render\ifNode( content : '
            I should not be rendered
        ', condition: $ifNode_0__condition );
	$Node_0[] = $Node_1 = new Render\Node( content : '
            
        ' );
		// Instantiating ifNode_1__condition for upcoming condition assignment
			$ifNode_1__condition = $this->tokens['true_token'] = new Render\Token( name : 'true_token' );

		$Node_1[] = $ifNode_1 = new Render\ifNode( content : '
                I should be rendered
            ', condition: $ifNode_1__condition );



        foreach($tokens as $key => $value){
            $this->tokens[$key]->content = $tokens[$key];
        }
        $this->nodes[] = $Node_0;
    }
}
