<?php

namespace Approach\Imprint\test\test;

use \Approach\Render as ProjectRender;
use \Approach\Render;

/**
 * 	This class was generated by Approach's Imprint::print()
 *	It is a PHP representation of the Imprint tree
 *	It can be used to create a new Imprint tree from the original XML file
 *
 */

class display extends Render\Node
{
    public array $tokens = [];

    public function __construct(array $tokens = [])
    {
        $Node =  new Render\Node();

        $opt = [];
        $opt['classes'][] = [];

        $sub_opt = [];
        $sub_opt['name'] = '';
        $sub_opt['content'] = 'test';
        $opt['classes'][] = new Render\Attribute($sub_opt['name'], $sub_opt['content']);
        $opt['attributes'] = [];

        $sub_opt = [];
        $sub_opt['name'] = 'data-check';
        $sub_opt['content'] =

            $b_token =  new Render\Node();

        $b_token[] =
            $b_token_0 =  new Render\Node(content: 'nacho ');

        $b_token[] =
            $b_token_1 =  new Render\Token(name: 'b');

        $b_token[] =
            $b_token_2 =  new Render\Node(content: ' mama');
        $this->token_nodes['b'] = $b_token;;
        $opt['attributes'] = new Render\Attribute($sub_opt['name'], $sub_opt['content']);
        $Node[] =
            $document =  new Render\HTML(tag: 'html', classes: $opt['classes'], attributes: $opt['attributes']);

        $document[] =
            $heaed =  new Render\HTML(tag: 'head');

        $heaed[] =
            $title =  new Render\HTML(tag: 'title', content: 'Test File');

        $document[] =
            $document_1 =  new Render\HTML(tag: 'body');

        $opt = [];
        $opt['classes'][] = [];

        $sub_opt = [];
        $sub_opt['name'] = '';
        $sub_opt['content'] = 'Screen';
        $opt['classes'][] = new Render\Attribute($sub_opt['name'], $sub_opt['content']);
        $document_1[] =
            $Screen =  new Render\HTML(tag: 'ul', classes: $opt['classes']);

        $opt = [];
        $opt['classes'][] = [];

        $sub_opt = [];
        $sub_opt['name'] = '';
        $sub_opt['content'] = 'Stage';
        $opt['classes'][] = new Render\Attribute($sub_opt['name'], $sub_opt['content']);
        $Screen[] =
            $Header =  new Render\HTML(tag: 'li', id: 'Header', classes: $opt['classes']);

        $opt = [];
        $opt['classes'][] = [];

        $sub_opt = [];
        $sub_opt['name'] = '';
        $sub_opt['content'] = 'Stage';
        $opt['classes'][] = new Render\Attribute($sub_opt['name'], $sub_opt['content']);
        $opt['attributes'] = [];

        $sub_opt = [];
        $sub_opt['name'] = 'color';
        $sub_opt['content'] = 'blue';
        $opt['attributes'] = new Render\Attribute($sub_opt['name'], $sub_opt['content']);

        $sub_opt = [];
        $sub_opt['name'] = 'flavor';
        $sub_opt['content'] =

            $x_token =  new Render\Node();

        $x_token[] =
            $x_token_0 =  new Render\Node(content: 'oran');

        $x_token[] =
            $x_token_1 =  new Render\Token(name: 'x');

        $x_token[] =
            $x_token_2 =  new Render\Node(content: 'gey');
        $this->token_nodes['x'] = $x_token;;
        $opt['attributes'] = new Render\Attribute($sub_opt['name'], $sub_opt['content']);
        $Screen[] =
            $Main =  new Render\HTML(tag: 'li', id: 'Main', classes: $opt['classes'], attributes: $opt['attributes']);

        $opt = [];

        $A_token =  new Render\Node();

        $A_token[] =
            $A_token_0 =  new Render\Node(content: 'content ');

        $A_token[] =
            $A_token_1 =  new Render\Token(name: 'A');

        $A_token[] =
            $A_token_2 =  new Render\Node(content: ' here');
        $this->token_nodes['A'] = $A_token;
        $Main[] =
            $Main_0 =  new Render\HTML(tag: 'div', content: $A_token);

        $opt = [];

        $B_token =  new Render\Node();

        $B_token[] =
            $B_token_0 =  new Render\Node(content: 'content ');

        $B_token[] =
            $B_token_1 =  new Render\Token(name: 'B');

        $B_token[] =
            $B_token_2 =  new Render\Node(content: ' here');
        $this->token_nodes['B'] = $B_token;
        $Main[] =
            $Main_1 =  new Render\HTML(tag: 'div', content: $B_token);

        $opt = [];

        $C_token =  new Render\Node();

        $C_token[] =
            $C_token_0 =  new Render\Node(content: 'content ');

        $C_token[] =
            $C_token_1 =  new Render\Token(name: 'C');

        $C_token[] =
            $C_token_2 =  new Render\Node(content: ' here');
        $this->token_nodes['C'] = $C_token;
        $Main[] =
            $Main_2 =  new Render\HTML(tag: 'div', content: $C_token);

        $opt = [];

        $D_token =  new Render\Node();

        $D_token[] =
            $D_token_0 =  new Render\Node(content: 'content ');

        $D_token[] =
            $D_token_1 =  new Render\Token(name: 'D');

        $D_token[] =
            $D_token_2 =  new Render\Node(content: ' here');
        $this->token_nodes['D'] = $D_token;
        $Main[] =
            $Main_3 =  new Render\HTML(tag: 'div', content: $D_token);

        $opt = [];
        $opt['classes'][] = [];

        $sub_opt = [];
        $sub_opt['name'] = '';
        $sub_opt['content'] =

            $B_token =  new Render\Node();

        $B_token[] =
            $B_token_0 =  new Render\Node(content: 'Stage ');

        $B_token[] =
            $B_token_1 =  new Render\Token(name: 'B');
        $this->token_nodes['B'] = $B_token;;
        $opt['classes'][] = new Render\Attribute($sub_opt['name'], $sub_opt['content']);
        $Screen[] =
            $Footer =  new Render\HTML(tag: 'li', id: 'Footer', classes: $opt['classes'], content: '(C) 2022 Your Company Name Here');

        $opt = [];
        $opt['classes'][] = [];

        $sub_opt = [];
        $sub_opt['name'] = '';
        $sub_opt['content'] = 'OffScreen';
        $opt['classes'][] = new Render\Attribute($sub_opt['name'], $sub_opt['content']);
        $document_1[] =
            $OffscreenRendering =  new Render\HTML(tag: 'ul', classes: $opt['classes']);

        $opt = [];
        $opt['classes'][] = [];

        $sub_opt = [];
        $sub_opt['name'] = '';
        $sub_opt['content'] = 'Stage';
        $opt['classes'][] = new Render\Attribute($sub_opt['name'], $sub_opt['content']);
        $OffscreenRendering[] =
            $PropContainer =  new Render\HTML(tag: 'li', id: 'Props', classes: $opt['classes'], content: '.............');


        foreach ($this->tokens as $key => $value) {
            if (isset($tokens[$key]))
                $this->tokens[$key]->content = $tokens[$key];
        }
    }
}
